language: android
jdk: oraclejdk8
before_install:
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet
install: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
script:
    - "./gradlew testDebugUnitTest"
    - "./fastlane/fastlane.sh"
deploy:
  provider: releases
  api_key: 
    secure: "HH64JUYoiICHn9uRSkxKrtsV/S/9ZlFxPAo39GJHOeaWzaU2XSQbSHd1daGcWdk6OaVHjuxn5KPKRwsOYMfviFZbQnW/w45dzzd7GbMGQSIEjoYwFzjus5gYHZUjStMjUzPROKuogYhCXo5cRAmq124fpwQNN4Re4k9L5K5YGNit2bSH0PbAC5lLk4k6p4Lh5+Ae9sRyJf8C45eA5x8HvaWik2dYO29BkVbspsTka3PTcVEqOa9tz5o+EYL4CM0GVfy/t2z6aePuDc8wE83MRCB3JxylmceAZQuJ7ZY4sz51MLJG2dp4xFAJ9/+KNCA2Ce3wAakFh9UC/wNLvs3FEz9ZDS/NTJvxPw9QoS5DwEX/S2MwSWL4yQ75IW9uwG+YYqQZAH/iV+QOVAi3CL80WpUn4zPAM6TIx43NoTl7CYLwFDIPzJlZ9rL79/jGHN9gUiW4lWko2bpWusiYGobGWUSSkpf0bqdCctnvANWO/17vAZif0xcHwYH7CQObPdwVZKhXyr5zUt5h2nZ90ZNU8839c6cdLRuGybGZZTZrjX80LQW7HOj9kz7XuBMukxO9mVYFKbf5c++zI10IfZ2/mvx/m5LVQ6/fYvxxkrpwsD8SQtnOuq5+vIwv2iYferiABCTYhSWqQKGdS1A4pmB/W0bPoH8Sz3+Qwp+GdT5wZzU="
  file: "/output/comics-$(date +'%d%m%Y%H%M').apk"
  skip_cleanup: true
  on:
    all_branches: true