language: android
jdk: oraclejdk8
before_install:
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet
install: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
script:
    - "./gradlew testDebugUnitTest"
    - "./fastlane/fastlane.sh"
deploy:
  provider: releases
  api_key: da5aea7355e2df44e2067b97f72a1a4148ae2bd5
  file: "sample-$(date +'%d%m%Y%H%M').apk"
  skip_cleanup: true
  on:
    all_branches: true